In [1]:
import torch
import torch.nn as nn 
import torch.optim as op 
import matplotlib.pyplot as plt

In [2]:
from utils.tranning_algo import learningData
from utils.Learning_Test import test_by_user_data

#input features
#n_feature=input("input features : ")


model=learningData()
#X=torch.tensor([[200.0, 30.0, 50.0, 60.0]])
#predict=test_by_user_data(model,X)
#print("Prediction:", predict)



Epoch [100/1000], Loss: 49.5393
Epoch [200/1000], Loss: 13.3975
Epoch [300/1000], Loss: 3.7110
Epoch [400/1000], Loss: 1.1140
Epoch [500/1000], Loss: 0.4170
Epoch [600/1000], Loss: 0.2292
Epoch [700/1000], Loss: 0.1778
Epoch [800/1000], Loss: 0.1630
Epoch [900/1000], Loss: 0.1580
Epoch [1000/1000], Loss: 0.1557
Learned Weights:
tensor([[2.1060]])
Learned Bias:
tensor([-0.2139])


In [3]:
from utils.import_data import data
x,y=data()
model=learningData()
X=torch.tensor([[200.0, 30.0, 50.0, 60.0]])
predict=test_by_user_data(model,X)
#print(predict)


x data tensor([ 1.2000,  1.4000,  1.6000,  2.1000,  2.3000,  3.0000,  3.1000,  3.3000,
         3.3000,  3.8000,  4.0000,  4.1000,  4.1000,  4.2000,  4.6000,  5.0000,
         5.2000,  5.4000,  6.0000,  6.1000,  6.9000,  7.2000,  8.0000,  8.3000,
         8.8000,  9.1000,  9.6000,  9.7000, 10.4000, 10.6000])
y data tensor([ 46206.,  37732.,  43526.,  39892.,  56643.,  60151.,  54446.,  64446.,
         57190.,  63219.,  55795.,  56958.,  57082.,  61112.,  67939.,  66030.,
         83089.,  81364.,  93941.,  91739.,  98274., 101303., 113813., 109432.,
        105583., 116970., 112636., 122392., 121873.])
Epoch [100/1000], Loss: 49.5393
Epoch [200/1000], Loss: 13.3975
Epoch [300/1000], Loss: 3.7110
Epoch [400/1000], Loss: 1.1140
Epoch [500/1000], Loss: 0.4170
Epoch [600/1000], Loss: 0.2292
Epoch [700/1000], Loss: 0.1778
Epoch [800/1000], Loss: 0.1630
Epoch [900/1000], Loss: 0.1580
Epoch [1000/1000], Loss: 0.1557
Learned Weights:
tensor([[2.1060]])
Learned Bias:
tensor([-0.2139])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x4 and 1x1)

In [4]:
%pip install openpyxl

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
